### PR TITLE
Updated test_routing.py

### PR DESCRIPTION
**Pull request by Aditi840**
Test literal migration with enum

### CODE REVIEW

**Review by Ovsyanka83 — CHANGES_REQUESTED** [review]
Sadly, this looks like ChatGPT made it. The test fails on its first line and its syntax only **resembles** the correct one. In actuality, it's very far from being correct.

The comments are very indicative of ChatGPT's work such as
`# Import the necessary modules and classes for your test`.

If any of the tasks were possible to complete using ChatGPT, I would use it but it's not the case so I ask you to run the tests yourself to make sure they work and to avoid contributing auto-generated code to open source projects in the future.

**Comment by Aditi840** [comment]
@Ovsyanka83, will do everything again.

**Comment by Aditi840** [comment]
@Ovsyanka83,  Apologies for that. I have just started contributing to open source projects and didn't have much knowledge, so I have used that to get it right and to avoid giving incorrect code to such a large codebase, as there are not many resources on the open source contributions. After this, I will make sure to cross-check every contribution I make, and I am always available for feedback and if you want to link some resources or some open source communities so that I can contribute better.

And check my new commit; if anything is wrong, I will make it right.

**Comment by Ovsyanka83** [comment]
I understand and I hope it's gonna work out. 

As for your latest commit: 
It is not a test, it's code on the top level. Please see other tests for reference, pytest docs, and "how to contribute to open source guide" for more details.

**Comment by Ovsyanka83** [comment]
Closing due to inactivity and because it is too far from main now.

**Pull request closed without merging**
